name: 'Phoenix Standard GitHub Action Build'
description: 'Runs the standard package creation'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  NUGET_PACKAGE_TOKEN: 
    description: NuGet Package Token
    required: true
outputs:
  newVersion:
    description: "The new version"
    value: ${{ steps.bump.outputs.newVersion }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
 
    - name: Set csproj, props version(s)
      id: update
      uses: vers-one/dotnet-project-version-updater@v1.6
      with:
        file: "./**/*.{csproj,props}"
        version: "bump-revision"

    - name: Update github version to ${{ steps.bump.outputs.newVersion }}
      shell: bash
      run: |
        git config user.name ${{ github.actor }}
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Bump project version to ${{ steps.update.outputs.newVersion }}"
        git push
        
    - name: Add Private Phoenix NuGet Registry
      run: dotnet nuget add source --username plazarre --password ${{ inputs.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name "Github Private Repo" "https://nuget.pkg.github.com/plazarre/index.json"
      
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build & Pack
      run: dotnet build --no-restore /p:Version="${{ steps.update.outputs.newVersion }}"

    - name: Test
      run: dotnet test --no-build --verbosity normal
