name: 'Phoenix Standard GitHub Action Build'
description: 'Runs the standard package creation'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion

    - id: foo
      uses: plazarre/phoenix-composite-action@v1
      with:
        who-to-greet: 'Mona the Octocat'

    - run: echo random-number "$RANDOM_NUMBER"
      shell: bash
      env:
        RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
        